### ISSUE TITLE
RegExp CharacterClass generation bug

### ISSUE THREAD

**Issue by michaelficarra** [estools/esfuzz#11]
These invalid RegExps were generated:

``` js
/([+-=_-M:2])+/
/[g--}]/
/([]|[+]|[z--o])/
/[W;?--gdH]+?/
/[p--y]/
/[$-$|-+?]/
/[$d--e]/
/[*x/A--T]/
/[P--C]/
/[E-w\\\\-?u]+?/
/[&-E--&{]/
/[7-Ww-&]/
/[+-:|-TeI>]/
/[(R7`h--`|]/
/[o--gu]*?/
/([dY--c])/
/([=-eX-?Yi])/
/[uT\\\\--rl]/
```

Why?

**Comment by vendethiel** [comment]
Looks like we need a fuzzesfuzz tool :D

**Comment by michaelficarra** [comment]
Haha it does that itself. That's why I know about the issue. It'd be really nice to extract the "generate random regular expression" logic into a separate module that I can explicitly test. I will do that soon.

**Comment by RReverser** [comment]
Looks like on rare occasions invalid RegExps are still being generated. For example, I got:

``` javascript
/=null)||null!==8552124315074560)>>{},")J$9cp`Z"({},vbwwsklgcqqbs?(.6)||false:(true,true,/
/=void true)?(/
```

and others with errors like

```
SyntaxError: Invalid regular expression: /.../: Unmatched ')'
```

**Comment by michaelficarra** [comment]
Can you give the whole program that was generated? I think you've parsed it incorrectly.

**Comment by RReverser** [comment]
I didn't parse it - just used `esfuzz.render(esfuzz.generate())` and found those when tried to instantiate `new RegExp` on corresponding nodes (after ~15-20K iterations though).

**Comment by michaelficarra** [comment]
I'm very suspicious that that was the generated program. Why does it start with `/=`?

**Comment by RReverser** [comment]
Huh, that's a good question :) Let me recheck.

**Comment by michaelficarra** [comment]
Not that starting with `/=` is a problem, but given how much what follows looks like a JavaScript program, I doubt that is random regexp characters.

**Comment by RReverser** [comment]
@michaelficarra Of course, you were right - looks like a bug is somewhere either on my or TypeScript parser side, and on extremely rare occasions. Will dig into it a little bit more, thanks!
